sonar.projectKey=sandykmaciel_Projeto-Integrador
sonar.organization=sandykmaciel
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests

sonar.test.inclusions=backend/tests/**/*.test.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,backend/src/database/**,backend/src/server.js,frontend/src/main.jsx
sonar.coverage.exclusions=frontend/src/**,backend/src/database/**,backend/src/server.js